---
# task file for lamp

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install LAMP stack
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apache2
    - mysql-server
    - php, libapache2-mod-php, php-mysql, php-xml, php-gd, php-imap, php-mysql
    - python3-pip

- name: Install mysql-connector-python
  pip:
    name: pymysql
    state: latest
  become: true


# ПЕРЕНЕСТИ В HANDLERS
# - name: Restart Apache
#   become: true
#   systemd:
#     name: apache2
#     state: restarted

- name: Copy .my.cnf template file
  template:
    src: templates/.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Change password for mysql root user
  mysql_user:
        name: "{{ mysql_root }}"
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host_all: true
        check_implicit_admin: true

- name: Create MySQL database
  mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_root }}"
        login_password: "{{ db_user_password }}"
        name: "{{ db_name }}"
        state: present


- name: Create MySQL user
  mysql_user:
        login_host: "{{ mysql_host }}"
        login_user: "{{mysql_root}}"
        login_password: "{{ mysql_root_password }}"
        name: "{{db_user}}"
        password: "{{ db_user_password }}"
        priv: "*.*:ALL"
        state: present

# - name: Установить права доступа на файл
#   file:
#     path: "{{mysql_dump_file}}"
#     mode: "0777"


# - name: Проверить права доступа к файлу dump
#   stat:
#     path: "{{mysql_dump_file}}"
#   register: dump_file_stat

# - name: Вывести информацию о правах доступа к файлу dump
#   debug:
#     var: dump_file_stat

- name: Import table structure dump into testdb
  mysql_db:
    name: "{{ db_name }}"
    state: import
    target: "{{ mysql_dump_file }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_user_password }}"

